[[headers]]
  for = "/api/omr/*"  # Apply to all /api/omr/* endpoints, including /api/omr/fetchTestbyId
  [headers.values]
    Access-Control-Allow-Origin = "https://omr-checker.vercel.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

[[headers]]
  for = "/api/questions"  # Keep existing rule for /api/questions
  [headers.values]
    Access-Control-Allow-Origin = "https://question-editor.vercel.app,https://omr-checker.vercel.app,https://multi-crop.vercel.app,http://localhost:3000,http://localhost:3001,http://localhost:5173"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Allow-Credentials = "true"
    Access-Control-Max-Age = "86400"

