[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*" # Or specify "https://question-editor.vercel.app"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
    Access-Control-Max-Age = "86400"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  force = true
