import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from '@clerk/nextjs';
import { Inter } from 'next/font/google';

const inter = Inter({
    subsets: ['latin'],
    weight: ['400', '500', '600', '700'],
    variable: '--font-inter',
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <ClerkProvider
            appearance={{
                captcha: {
                    theme: 'dark',
                    size: 'flexible',
                    language: 'es-ES',
                }
            }}
        >
            <html lang="en">
                <script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/3.2.2/es5/tex-mml-chtml.min.js" async></script>

                <body className={inter.variable}>
                    <main className="min-h-screen bg-gray-50">
                        {children}
                    </main>
                </body>
            </html>
        </ClerkProvider>
    );
}
